### ISSUE TITLE
Maybe I'm a bit to picky but would it be possible to change the ID

### ISSUE THREAD

**Issue by azoitl** [flathub/org.eclipse.iot.fourdiac.Ide#5]
the written name of 4diac is written fordiac. Would it be to much to ask to change org.eclipse.iot.fourdiac.Ide to reflect our eclipse package name: org.eclipse.fordiac.ide?

**Comment by ctron** [comment]
IIRC the problem was that numbers weren't allowed, thus it got replaced with "four" … And I am not sure if it is possible to "change" a name. I think you can only create a new repository, with a new name. However you wouldn't be able to update from the old to the new one.

**Comment by azoitl** [comment]
I feared that. It is not that important for me. So I'll close this issue.

**Comment by bilelmoussaoui** [comment]
> IIRC the problem was that numbers weren't allowed, thus it got replaced with "four" … And I am not sure if it is possible to "change" a name. I think you can only create a new repository, with a new name. However you wouldn't be able to update from the old to the new one.

That's not entirely true, you can EOL an application and make flatpak install the new one when the user runs a flatpak update. See https://github.com/flathub/flathub/wiki/App-Maintenance#end-of-life 

Note that it's only supported by Flatpak CLI for now, other Flatpak clients don't support this feature

**Comment by ctron** [comment]
Thanks @bilelmoussaoui for the note. So @azoitl I leave this up to you! I am happy to move this to a new name if you want to go for that.

**Comment by azoitl** [comment]
Not sure if it is worth the effort. I'm very happy that we have the flatpack. Thanks for that effort by the way.
